name: dsctriage
summary: Application to keep track of updates on a Discourse server
description: |
  Output comments from a Discourse server for triage. This application is used by the Ubuntu Server team to keep up with
  suggested fixes and issues in the Ubuntu Server Guide at https://ubuntu.com/server/docs. It can, however, also be used
  to look into Discourse posts on any Discourse server, or other sections of Ubuntu's documentation.

base: core20
type: app
version: git
confinement: strict
grade: stable

apps:
  dsctriage:
    command: bin/dsctriage
    plugs:
      [network, network-bind]

parts:
  dsctriage:
    plugin: python
    source: https://github.com/lvoytek/discourse-triage
    source-type: git
